services:
  server:
    image: sfdeloach/event-hub-server-dev:0.0.0
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - "7331:7331"
    volumes:
      - /app/static/css
      - ./server:/app
